# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04fc6273c3d9be68c48f8dbb438d82a0aad1419dda7ea408502d3fcebaf32265fb406a3f6f4bb2ec2b2109d5c5d07c796a31ea648341f77220f6dd1923e5c206

test:
  secret_key_base: 4fe4151508ae7646b9c96f6df797515dd7df398cda64dc4070745481d41f88d61ceffa3f53e9a59904ed8ffe4bfab558b2908135639c42166f829dd8827657a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
